Develop to Main
georgiev84/DigitallWarehouse pull request #2
Opened 2024-01-15 12:05 UTC by georgiev84

2024-01-16 10:27 UTC, Admiraculix commented
**Your Solution is not built in this state** Please fix it

2024-01-16 12:00 UTC, Admiraculix requested changes

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Api/Controllers/AuthenticationController.cs
> +public class AuthenticationController : ControllerBase
If you're not going to use something, don't put it on. This is the YAGNI principle.

[YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Api/Controllers/WarehouseController.cs
> +    public async Task<ActionResult<IEnumerable<Product>>> GetProducts([FromQuery(Name = "MinPrice")] decimal? minPrice,
All FromQuery params can be wrapped in  one request model class with props

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Api/Controllers/WarehouseController.cs
> +[Route("api")]
Use this approach:
[Route("api/[controller]")]
[ApiController]
Create your base controller that inherits ControllerBase from .netcore. Yours should take all common things and be inherited by Warehouse contoller.
The idea is that if you add a new controller which is a lot of you probably inherit your controller and save all the boiler code

The other approach is from new core version is FromService:
https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/dependency-injection?view=aspnetcore-8.0#action-injection-with-fromservices

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Api/Controllers/WarehouseController.cs
> +    public WarehouseController(ISender mediator)
This should be part of the base controller or new approach. Look previous comment

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Api/Controllers/WarehouseController.cs
> +            var query = new ProductQuery
It would be useful to use the automapper, a quite popular technology with which the mapping layer is delegated to a separate place, which raises the level of the whole project to be quite SOLID

https://automapper.org/

When query params to an object(ProductFilterRequest) this object should be map to ProductFilterQuery.

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Api/Controllers/WarehouseController.cs
> +        catch (Exception ex)
I think this try/catch should be handler-level. Not need your thin action methods to have one more responsibility. Because if you handle this here where is the Logger of this msg?

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Api/Filters/ErrorHandlingFilter.cs
> +public class ErrorHandlingFilter : IExceptionFilter
You will either need to polish it or use a standard approach like WebMiddleware
Article: 
https://medium.com/@engrabdullahabdullah/middleware-vs-exception-filters-in-asp-net-core-a-simplified-guide-2f00a5f1bf04

- If you want simple global error handling WebMiddleware.
https://youtu.be/uOEDM0c9BNI?t=332

- If you want more detailed stuff then  ExceptionFilters like:
 https://learn.microsoft.com/en-us/dotnet/api/system.data.dbconcurrencyexception?view=net-8.0
```
     else if (exceptionType == typeof(DBConcurrencyException ))
        {
            error.Message = exception.Message;
            error.StatusCode = HttpStatusCode.Conflict;
	//Do other logic...
      }
```

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Api/Filters/ErrorHandlingFilter.cs
> +            error.StatusCode = 400;
Having a problem in the backend system is not a bad request, it is a 500
And don't use magic numbers like 500 or 400 or 409...
There is an enum for that: 
https://learn.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=net-8.0
HttpStatusCode.BadRequest

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Api/Filters/ErrorHandlingFilter.cs
> +            error.StatusCode = 409;
Having a problem in the backend system is not a bad request, it is a 500
And don't use magic numbers like 500, 400 or 409...
There is an enum for that: 
https://learn.microsoft.com/en-us/dotnet/api/system.net.httpstatuscode?view=net-8.0
HttpStatusCode.Conflict

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Api/Filters/ErrorHandlingFilter.cs
> +        _logger.LogError("Exception occured in {Method} with Message: {Exception}", context.ActionDescriptor?.DisplayName, error.Message);
Why are we Logging here you have LoggingPipelineBehavior which is s responsible for handling all flow of the application.
Are you sure about this decision?

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Application/Common/Interfaces/IExternalApiService.cs
> +public interface IExternalApiService
The name is not appropriate. If there is another external service, what will it be called IAnotherExternalService or IExternalService2?
Common practice is to name external services as domain names like IMockyApiService or IMockyHttpClient

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Application/Common/Persistence/IWarehouseRepository.cs
> +namespace Warehouse.Application.Common.Persistence;
Move folder inside folder Interfaces

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Application/DependencyInjection.cs
> +    public static IServiceCollection AddApplication(this IServiceCollection services)
This is an extension method.
It is accepted when you have extension methods to be in the extensions folder and the name of the class contains the word extension as a suffix.
Like your packages in your assembly:
 PackageReference Include="AutoMapper.**Extensions**.Microsoft.DependencyInjection" Version="12.0.1" 
 PackageReference Include="Microsoft.**Extensions**.DependencyInjection" Version="8.0.0" 
PackageReference Include="Microsoft.**Extensions**.Logging" Version="8.0.0" 

Also in my opinion this method should be named "DependencyRegistration"

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Application/Queries/Warehouse/ProductQueryHandler.cs
> +public record ProductQueryHandler : IRequestHandler<ProductQuery, ProductResponse>
ProductQuery, and ProductResponse these files don't exist in this version of the code.
ProductsQuery <- Try if you can make this a record and if you like it better.

ProductResponse  <-I would like at the business level to use DTO Models and not response models.
Let the Presentation layer decide exactly what to return to the fondend.
Because there will be in the future domain models also this will help a lot.

It would be useful to use the automapper, a quite popular technology with which the mapping layer is delegated to a separate place, which raises the level of the whole project to be quite SOLID

https://automapper.org/

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Application/Queries/Warehouse/ProductQueryValidator.cs
> +                .WithMessage("MinPrice must be greater than zero when provided")
These sting msgs can be in separate classes Models/Constants/CustomValidationErrorMessages.cs

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Domain/Errors/Error.cs
> +public class Error
How error can be in your domain area?
Your domain is Product and respectively you need a Product domain model with will pass from the repository and map to dto.

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Infrastructure/DependencyInjection.cs
> +    public static IServiceCollection AddInfrastructure(this IServiceCollection services)
Same comment as the other dependency reg file

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Infrastructure/Persistence/WarehouseRepository.cs
> +    public WarehouseRepository(HttpClient httpClient, IExternalApiService externalApiService)
Your repository should be only responsible for the manipulation of the data.
Now is a service not a repository.
You should have a httpclient class do kinds of stuff related to getting the correct information and passing the collection to the repo.

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Infrastructure/Persistence/WarehouseRepository.cs
> +            FetchProducts().GetAwaiter().GetResult();
Why are we doing it synchronously this is wrong.

Remove this if statement it is not needed

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Infrastructure/Persistence/WarehouseRepository.cs
> +    private readonly HttpClient _httpClient;
this is not use

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Infrastructure/Persistence/WarehouseRepository.cs
> +    public async Task<IEnumerable<Product>> GetProductsAsync()
Should fix it, your whole concept of repository.
https://medium.com/@kerimkkara/implementing-the-repository-pattern-in-c-and-net-5fdd91950485

Try to make the HttpClient fill a sheet for you in another class (DbSimulator.cs) or use in memory cache for the client to fill and the repo takes it from there. To simulate db behavior. And to decouple the repo from HTTP requests.

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Infrastructure/Persistence/WarehouseRepository.cs
> +public class WarehouseRepository : IWarehouseRepository
These repositories can be in separate assemblies as another infrastructure module.

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Infrastructure/Services/ProductService.cs
> +    public async Task<ProductResponse> GetFilteredProductsAsync(decimal? minPrice, decimal? maxPrice, string size, string highlight)
this can be part of the Repository

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Infrastructure/Services/ProductService.cs
> +    private IEnumerable<Product> HighlightWords(IEnumerable<Product> products, string highlight)
this can be turned to the Extension method

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Infrastructure/Services/ProductService.cs
> +            {
Each of these ifs can be moved into the extension methods to offload this method.

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Infrastructure/Services/ProductService.cs
> +            return new ProductResponse
You should return the domain model not a response model

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Tests/ExternalApiTests.cs
> +        Assert.IsType<HttpRequestException>(exception.InnerException);
Let's use for assertion 
[FluentAssertion](https://fluentassertions.com/introduction)

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Tests/Warehouse.Tests.csproj
> +    <PackageReference Include="Moq" Version="4.20.70" />
New versions of Moq are not welcome because they sell information.
[youtube.com/watch?v=A06nNjBKV7I&ab_channel=NickChapsas](https://www.youtube.com/watch?v=A06nNjBKV7I&ab_channel=NickChapsas)

2024-01-16 12:00 UTC, Admiraculix commented on Warehouse.Tests/ProductServiceTests.cs
> +        var mockWarehouseRepository = new Mock<IWarehouseRepository>();
If you want an experiment with  
[AutoFixture](https://autofixture.github.io/docs/quick-start)
Autofixture with AutoFixture.AutoMoq

2024-01-16 15:57 UTC, georgiev84 commented on Warehouse.Infrastructure/Services/ProductService.cs
> +    public async Task<ProductResponse> GetFilteredProductsAsync(decimal? minPrice, decimal? maxPrice, string size, string highlight)
I researched about two approaches and decide to leave repository cleaner and move most of the logic in the service

2024-01-17 11:21 UTC, georgiev84 commented on Warehouse.Api/Controllers/AuthenticationController.cs
> +public class AuthenticationController : ControllerBase
Done

2024-01-17 11:21 UTC, georgiev84 commented on Warehouse.Api/Controllers/WarehouseController.cs
> +    public async Task<ActionResult<IEnumerable<Product>>> GetProducts([FromQuery(Name = "MinPrice")] decimal? minPrice,
Done

2024-01-17 11:21 UTC, georgiev84 commented on Warehouse.Api/Controllers/WarehouseController.cs
> +[Route("api")]
Done

2024-01-17 11:21 UTC, georgiev84 commented on Warehouse.Api/Controllers/WarehouseController.cs
> +    public WarehouseController(ISender mediator)
Done

2024-01-17 11:22 UTC, georgiev84 commented on Warehouse.Api/Controllers/WarehouseController.cs
> +            var query = new ProductQuery
Automapper is implemented

2024-01-17 11:22 UTC, georgiev84 commented on Warehouse.Infrastructure/Services/ProductService.cs
> +            {
Extension methods are applied

2024-01-17 11:22 UTC, georgiev84 commented on Warehouse.Infrastructure/Services/ProductService.cs
> +            return new ProductResponse
Done

2024-01-17 11:22 UTC, georgiev84 commented on Warehouse.Tests/ExternalApiTests.cs
> +        Assert.IsType<HttpRequestException>(exception.InnerException);
Fluent assertion is installed and used in unit tests

2024-01-17 11:43 UTC, georgiev84 commented on Warehouse.Infrastructure/Persistence/WarehouseRepository.cs
> +public class WarehouseRepository : IWarehouseRepository
I prefer to use it in the Infrastructure for now

2024-01-17 11:44 UTC, georgiev84 commented on Warehouse.Tests/ProductServiceTests.cs
> +        var mockWarehouseRepository = new Mock<IWarehouseRepository>();
Will do the experiment in separate project

2024-01-17 14:36 UTC, Admiraculix requested changes

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Api/Controllers/ApiController.cs
> +    public class ApiController : ControllerBase
Make it BaseController it more clear

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Api/Controllers/ApiController.cs
> +namespace Warehouse.Api.Controllers
Since we are using the latest framework let's use this approach for all files. This comment applies to all files:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Api/Dto/ProductDto.cs
> +public class ProductDto
Dtos exist only in the Application layer which means this should be ProductResponse.

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Api/Dto/ProductDto.cs
> +namespace Warehouse.Api.Dto;
I recommend the following structure of folders. Dto folder should be renamed.
**Models** or **Contracts**
and second folder which separates request and response models:
```
Models__
        |
        Requests
        |
        Responses
```

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Api/Errors/Error.cs
> +public class Error
This model should be in the model folder check previous comments

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Api/Filters/ErrorHandlingFilter.cs
> +        else if (exceptionType == typeof(DBConcurrencyException))
Only currency is correct.
 
**ArgumentNullException 
InvalidOperationException 
AutoMapperMappingException**
All of this matches status code 500 

if you want to use a filter instead of WebMiddleware 
You should create custom error exceptions and throw them and catch them here for these status codes
For  example, BadReques can return when they have Validation errors

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Api/Mappings/MappingProfile.cs
> +        CreateMap<ProductResponseDto, ProductDto>();
The response is not Dto 
ProductResponse  only

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Application/DependencyRegistration.cs
> +public static class DependencyRegistration
This is an Extension class that should have the suffix: DependencyRegistration*Extension*.
Moved into the Extensions folder also

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Application/Models/Dto/ProductResponseDto.cs
> +public class ProductResponseDto
ProductDto is enough. Please rename it

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Domain/Responses/ProductFilter.cs
> +public class ProductFilter
Why do we have responses in the domain layer?

Do you intend to use them as part of the database as tables?
In the domain, there are only entities that participate as objects from the database

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Domain/Responses/ProductDomainModel.cs
> +public class ProductDomainModel
Why do we have responses in the domain layer?

Do you intend to use them as part of the database as tables?
In the domain, there are only entities that participate as objects from the database

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Infrastructure/DependencyRegistration.cs
> +public static class DependencyRegistration
Same as previous commentary related to extensions methods

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Infrastructure/Persistence/WarehouseRepository.cs
> +    private readonly string apiUrl= "https://run.mocky.io/v3/97aa328f-6f5d-458a-9fa4-55fe58eaacc9";
This is a bad practice and should be configured like this:
```
 "MockyClient": {
    "BaseUrl": "http://www.mocky.io/",
    "ProductUrl": "v2/5e307edf3200005d00858b49"
  }
```
And should be in the Configuration object into configuration folder

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Infrastructure/Services/ProductService.cs
> +            var wordOccurrences = allDescriptions
this also is a pure function and operation under stings this means can be an extension method also under List<string>
```
                .SelectMany(desc => desc.Split(new[] { ' ', '.', ',' }, StringSplitOptions.RemoveEmptyEntries))
                .GroupBy(word => word.ToLower())
                .Select(group => new { Word = group.Key, Count = group.Count() })
                .OrderByDescending(x => x.Count)
                .Select(x => x.Word)
                .ToList();
```

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Infrastructure/Services/ProductService.cs
> +            filteredProducts = filteredProducts.FilterByMinPrice(minPrice);
My Idea was for these extensions to be chained like this:
```
            filteredProducts = filteredProducts
                            .FilterByMinPrice(minPrice)
                            .FilterByMaxPrice(maxPrice)
                            .FilterBySize(size)
                            .HighlightWords(highlight);
```

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Infrastructure/Services/MockApiService.cs
> +public class MockApiService : IMockApiService
This is not a service a Client Should be in the Client folder.
Rename it to MockyApiClient and interface

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Infrastructure/Services/ProductService.cs
> +public class ProductService : IProductService
I think this is business logic and should sit in the application

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Infrastructure/Services/ProductService.cs
> +            return new ProductDomainModel
And if is on application then can be renamed as Dto

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Infrastructure/Services/ProductService.cs
> +                Filter = new ProductFilter
And if is on application then can be renamed as Dto

2024-01-17 14:36 UTC, Admiraculix commented on Warehouse.Tests/ExternalApiTests.cs
> +
white space

2024-01-18 12:14 UTC, Admiraculix requested changes

2024-01-18 12:14 UTC, Admiraculix commented on Warehouse.Api/Filters/ErrorHandlingFilter.cs
> +
white space

2024-01-18 12:14 UTC, Admiraculix commented on Warehouse.Application/Common/Interfaces/IProductService.cs
> +    Task<ProductDto> GetFilteredProductsAsync(decimal? minPrice, decimal? maxPrice, string? size, string? highlight);
If you want this "decimal? minPrice, decimal? maxPrice, string? size, string? highlight" can be wrapped in new dto 
with the same name  ItemPriceDto or ItemsDto or something else. 

This is advice if you want it is not critical or bad. the decision is yours

2024-01-18 12:14 UTC, Admiraculix commented on Warehouse.Infrastructure/DependencyRegistrationExtension.cs
> +namespace Warehouse.Infrastructure;
Move it to Extensions folder pleasе

2024-01-18 12:14 UTC, Admiraculix commented on Warehouse.Application/DependencyRegistrationExtension.cs
> +namespace Warehouse.Application;
Move it to Extensions folder pleasе

2024-01-18 12:14 UTC, Admiraculix commented on Warehouse.Infrastructure/Configuration/MockyClientConfiguration.cs
> +    public string? BaseUrl { get; set; }
In my opinion, they should not be null because the application will not work if this is not correct. here you want to explode. Better remove those question marks.

2024-01-18 15:21 UTC, georgiev84 commented on Warehouse.Application/Common/Interfaces/IProductService.cs
> +    Task<ProductDto> GetFilteredProductsAsync(decimal? minPrice, decimal? maxPrice, string? size, string? highlight);
Yes I was thinking about that but decide to leave it as it is now.

2024-01-19 07:49 UTC, Admiraculix commented on Warehouse.Application/Extensions/DependencyRegistrationExtension.cs
> +namespace Warehouse.Application;
You forgot to update the namespace

2024-01-19 07:49 UTC, Admiraculix commented on Warehouse.Infrastructure/Extensions/DependencyRegistrationExtension.cs
> +namespace Warehouse.Infrastructure;
You forgot to update the namespace

2024-01-19 08:46 UTC, Admiraculix approved these changes

2024-01-19 08:51 UTC, merged